name: FPL Daily Snapshot (Pre-Change)

on:
  schedule:
    - cron: "0 1 * * *"   # 01:00 UTC = 11:00 Brisbane (UTC+10)
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: fpl-daily-snapshot
  cancel-in-progress: false

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || pip install requests

      - name: Run snapshot
        run: python price_snapshot.py

      - name: Commit JSON
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/fpl_price_log.json
          git commit -m "Pre-change snapshot (01:00 UTC) [$(date -u +'%F %T')]" || echo "No changes"
          git push
